# Generated by Django 3.0.3 on 2020-02-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_Number',
            new_name='isbn',
        ),
    ]
